### ISSUE TITLE
Implement a translator for the some particular suggestions

### ISSUE THREAD

**Issue by pythonbrad** [pythonbrad/clafrica-wish#24]
Problem
---

When working with date, time and number by example, it's not easy to provide a suggestion file for it.
Example:
```toml
[suggestions]
1 = "one"
2 = "two"
...
n = "..."
```
